// add bootstrap css
import "bootstrap/dist/css/bootstrap.css";
// own css files here
import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Teachmint</title>
        <meta name="description" content="Generated by teachmint app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className}`}>
        <Component {...pageProps} />
      </main>
    </>
  );
}
